api: polyfea.github.io/v1alpha1
kind: MicroFrontend
metadata:
  name: polyfea-md-shell
spec:
  frontendClass: default
  service:
    name: polyfea-md-shell
    port: http
  modulePath: md-shell.esm.js
  dependsOn:
    - material-design