apiVersion: apps/v1
kind: Deployment
metadata:
  name: &POD polyfea-md-shell
spec:
  replicas: 1
  selector:
    matchLabels:
        pod: *POD
  template:
    metadata:
      labels: 
        pod: *POD
    spec:
      containers:
      - name: *POD
        image: ghcr.io/polyfea/md-shell:latest
        imagePullPolicy: IfNotPresent
        ports:
          - name: http
            containerPort: 7105
        resources:
            requests:
                memory: "16M"
                cpu: "0.01"
            limits:
                memory: "320M"
                cpu: "0.2"